version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "10116:10116/udp"
    environment:
      - ENDPOINT=postgres
    external_links:
      - envio-firmware-postgres-1
    networks:
      - app-network

# networks: 
#   app-network:
#     external: 
#      name: backing-services

networks: 
  app-network:
     name: backing-services
     external: true